name       : hh
version    : '1.25'
release    : 2
source     :
    - https://github.com/dvorka/hstr/releases/download/1.25/hh-1.25-src.tgz : 0f5aad093c60bd79b8da22e8a560dd27f737d4847c4c7e12d99f153d1490d282
license    : Apache-2.0
component  : system.utils
summary    : hstr - manage your command history
description: |
    Bash and Zsh shell history suggest box - easily view, navigate, search and manage your command history.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
