name       : hh
version    : '2.0'
release    : 3
source     :
    - https://github.com/dvorka/hstr/releases/download/2.0/hstr-2.0.0-tarball.tgz : 9844587d4e91daa8a78eeeac13e995995fff36616fda5f374da7301c9bce15e4
license    : Apache-2.0
component  : system.utils
summary    : hstr - manage your command history
description: |
    Bash and Zsh shell history suggest box - easily view, navigate, search and manage your command history.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
